apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /
    prometheus.io/port: '8080'
spec:
  selector: 
    app: jenkins-server
  type: LoadBalancer   # <-- yahan NodePort se LoadBalancer kar diya
  ports:
    - port: 8080
      targetPort: 8080
      # nodePort ko hata diya, kyunki LoadBalancer me zarurat nahi
